### ISSUE TITLE
Getting 56 subcarriers in 40 MHz

### ISSUE THREAD

**Issue by itskalvik** [xieyaxiongfly/Atheros_CSI_tool_OpenWRT_src#25]
Hi,
I have a WDR4300 setup at 5GHz 40 MHz and a desktop client connected to the router. I used wavemon to verify that the connection is indeed at 40MHz but the recv_csi tool is giving me only 56 sub carriers. I tried using another WDR4300 router as the client at 40MHz and still got 56 sub carriers, I also setup a desktop as the AP at 5GHz 40MHz with hostapd and used another desktop as the client and got only 56 sub carriers. I have the AR9380 NIC on the desktops. Did anyone manage to get all 114 sub carriers?

**Comment by djydo** [comment]
Hi @kdkalvik,

Yes, it is possible to get CSI on 114 subcarriers at 5 GHz. Set AP (4300 router) to 40 MHz using luci or  OpenWrt GUI **before** associating the client to the AP.  The AP is running OpenWrt version of atherosCSI and client is using ubuntu 4.1+ kernel.

**Comment by itskalvik** [comment]
I tried that but for some reason I keep getting only 56 sub carriers. Got any suggestions?

**Comment by djydo** [comment]
I experienced the same thing on 2.4 GHz but not on 5 GHz. The transmission could not use 40 MHz even after I set bandwidth to 40 MHz using wireless utility, luci or GUI. So, I assumed it was an issue with my wifi card (iface0).

Were you able to verify that the AP was using 40 MHz on 5 GHz? Try to confirm that on the wireless overview for associated stations.

**Comment by itskalvik** [comment]
Yeah, I used the web interface to check 40MHz and it was indeed using 40MHz. Even when I used desktops on both AP and client, I was able to verify that I have 40MHz with wavemon. Not sure what the issue is.

**Comment by djydo** [comment]
check [openwrt forum](https://forum.openwrt.org/t/40mhz-802-11n-setup-saved-but-is-20mhz-wide/19547/18) maybe some of the info can help.

**Comment by itskalvik** [comment]
Figured it out, I was setting the MCS rate to 16 on the transmitter by updating the rate_index_table by echoing 18 into it. But it is supposed to be 78, to set it to MCS 16 at 40MHz.
