### ISSUE TITLE
Failed Install of Ubuntu version

### ISSUE THREAD

**Issue by nghiahhnguyen** [xieyaxiongfly/Atheros_CSI_tool_OpenWRT_src#26]
I have followed the installation instruction and got no error. However, after installing and rebooting, this is the output of "$uname -r": "4.4.0-139-generic". From your wiki, I assume that the output must be "4.1.10+". I do not know what might have caused the problem.

**Comment by shulinyang** [comment]
请问您解决这个问题了吗，现在我也是遇到这个问题

**Comment by jinzhang-unsw** [comment]
Hi I have the same problem. Anyone know how to install this?

**Comment by nghiahhnguyen** [comment]
I have not solved the problem yet unfortunately.

**Comment by jinzhang-unsw** [comment]
Have you guys try ubuntu 12.04? I guess it is the version problem maybe the 14.04 change after the author released.

**Comment by itskalvik** [comment]
During boot enter the grub menu by tapping shift key. When you see the menu enter Advanced options tab and select the kernel version with 4.1.10+ in the name. Select it and press enter to boot with that kernel.

**Comment by nghiahhnguyen** [comment]
Thank you for your instruction @kdkalvik
