### ISSUE TITLE
compatibility of the tool on tp-link wdr4900

### ISSUE THREAD

**Issue by csmibrahim** [xieyaxiongfly/Atheros_CSI_tool_OpenWRT_src#56]
Can I install the tool on TP-Link TL-WDR4900 (N900) v1.3?

https://openwrt.org/toh/tp-link/tl-wdr4900

**Comment by csmibrahim** [comment]
Also is TP-Link TL-WR841N, Version:11.1 supported by the tool?

https://openwrt.org/toh/tp-link/tl-wr841nd

**Comment by csmibrahim** [comment]
I do not know why I find it hard to check for the router compatibility  with the tool? 

Like for example when I open the router page on OpenWrt website: what I have to check exactly? 

Are only those routers mentioned on this list (https://github.com/xieyaxiongfly/OpenWRT_firmware) supported by the tool? Does the target must be of ar71xx only? Does the SOC must be ARxxx or QCAxxx ? 

I read : https://wands.sg/research/wifi/AtherosCSI/Hardware.html but it is not easy job finding compatible router except get one old router mentioned here or there. 

Kindly more information

@xieyaxiongfly kindly help.

**Comment by csmibrahim** [comment]
I checked the firmware list (https://github.com/xieyaxiongfly/OpenWRT_firmware) but what are all these devices? 
What are these aps devices:
ap132, ap121, ap147
or the very rare devices: 
cap4200ag,cf-e316n-v2
or very old devices: 
DIR-825 B1, Planex  mzk w04nu
or specialized devices not available for individuals
or Cryptocurrency Miner devices !

What is this exactly? Is it just OpenWrt OS that we can get from the OpenWrt website or is it upgraded version from OS with the tool?

**Comment by Geosearchef** [comment]
It's the openwrt firmware patched with the kernel driver modification for the CSI tool.  In case you have supported device not listed there, you can build the firmware yourself.

**Comment by Geosearchef** [comment]
The WDR4900 should work using the 5GHz AR9580 chip, using QCA9558 (2,4GHz) with the tool might or might not work. (see https://github.com/xieyaxiongfly/Atheros_CSI_tool_OpenWRT_src/issues/35)
