### ISSUE TITLE
How to change the number of transmitting and receiving antennas? (TP-Link WDR4300)

### ISSUE THREAD

**Issue by AlexandrAstafiev** [xieyaxiongfly/Atheros_CSI_tool_OpenWRT_src#67]
Hello!

I purchased 2 routers and installed a modified openWRT based firmware on them. The number of antennas on the routers is 3. However, I receive 2x2x56 data packets. How can I change the number of antennas in packets? What needs to be changed? File on Matlab? sendData or recvCSI? Is there any instruction?

**Comment by Geosearchef** [comment]
What routers? I'm guessing WDR4300? That one uses the two outer antennas with the AR9344. For 3 antennas you'll have to use the AR9580. (switching from 2.4 GHz band to 5 GHz)

**Comment by AlexandrAstafiev** [comment]
Thanks for the quick response. Then what models can you recommend for receiving data from 3 or more antennas. It is desirable to obtain information from 114 subcarriers or more.

**Comment by Geosearchef** [comment]
WDR4300 on 5 GHz. WR2543ND on both bands.

Obtainef subcarriers will be 56 on 20MHz bandwidth, 114 on 40 MHz.

**Comment by AlexandrAstafiev** [comment]
That is, the WDR4300 router can be switched to 5GHz and receive data from 3 antennas?

**Comment by Geosearchef** [comment]
Yes
